### ISSUE TITLE
display all observations and all tick labels

### ISSUE THREAD

**Issue by amadeusX** [Biclustering/biclust#1]
Thank you so much for the great biclust package! Got some nice results with it on 86 genes and 8 histone modifications.
Could you please help me what is the best way to display the axis labels (the individual genes and histone modifications) using heatmapBC or anything else?

I see that the information could be extracted from the bicluster memberships of the Biclust class, from the  RowxNumber and NumberxCol logical matrices but I guess you have some ready-made solution for that.

 sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7
Matrix products: defaultBLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylibLAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylibRandom number generation: RNG:     Mersenne-Twister  
Normal:  Inversion  
Sample:  Rounding  locale:[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:[1] biclust_2.0.2    lattice_0.20-41  colorspace_1.4-1 MASS_7.3-51.6   
loaded via a namespace (and not attached): [1] Rcpp_1.0.5            rstudioapi_0.11       magrittr_1.5          tidyselect_1.1.0      munsell_0.5.0         [6] flexclust_1.4-0       R6_2.4.1              rlang_0.4.7           fansi_0.4.1           dplyr_1.0.1          [11] tools_4.0.2           parallel_4.0.2        gtable_0.3.0          cli_2.0.2             modeltools_0.2-23    [16] ellipsis_0.3.1        class_7.3-17          assertthat_0.2.1      tibble_3.0.3          lifecycle_0.2.0      [21] crayon_1.3.4          tidyr_1.1.2           purrr_0.3.4           ggplot2_3.3.2         vctrs_0.3.2          [26] rsconnect_0.8.16      glue_1.4.1            compiler_4.0.2        pillar_1.4.6          additivityTests_1.1-4[31] generics_0.0.2        scales_1.1.1          stats4_4.0.2          pkgconfig_2.0.3  

bicRes = biclust(mdf +0.01, method=BCSpectral, normalization="irrc", numberOfEigenvalues=3,                minr=2, minc=5, withinVar=1)

heatmapBC(mdf, bicRes, number=1:24, local=T, order=T,
          axes=T, outside=T, zlim = c(0,1))

Thank you so much.

Cheers,

Istvan

Istvan (Steve) Ladunga
Professor Emeritus of Computational Biology
Department of Statistics

Lincoln, NE and Budapest
sladunga@unl.edu

**Comment by Sami-Leon** [comment]
Hi Istvan, sorry for the late reply. The current version of heatmapBC does not provide a plot with the original axis labels. I then decided to add this option to heatmapBC, it will be available soon. I just emailed you the updated version, in case you still need to use it, and need it now.

Once the function is updated you will only need to type:

bicRes = biclust(mdf +0.01, method=BCSpectral, normalization="irrc", numberOfEigenvalues=3, minr=2, minc=5, withinVar=1)

heatmapBC(mdf, bicRes, number=1:24,) # if you only want to display the biclusters

heatmapBC(mdf, bicRes, number=0) # if you want to display the entire data with the biclusters as well.

Best,
Sami
